package com.coobi.logistics.logisticsapi.integration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import com.coobi.logistics.eventgenerator.event.VehicleLocationEvent;
import com.coobi.logistics.logisticsapi.LogisticsApiApplication;
import com.coobi.logistics.logisticsapi.integration.support.GeneratedTelemetry;
import com.coobi.logistics.streamprocessor.StreamProcessorApplication;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.kafka.KafkaContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * MVP-9.4: the whole pipeline of the project, from generated telemetry to the public API.
 *
 * <pre>
 * event generator -> Kafka -> stream processor -> PostgreSQL -> logistics-api -> HTTP
 * </pre>
 *
 * <p>Every component is the real one:
 *
 * <ul>
 *   <li>Kafka and PostgreSQL run in the images {@code compose.yml} uses
 *       ({@code apache/kafka:4.3.1} and {@code postgres:18.6});
 *   <li>the telemetry is generated by the simulator and the version-1 event contract of the
 *       event generator, and published the way its publisher publishes it - one record per
 *       event, keyed by the vehicle identifier;
 *   <li>the stream processor runs as the application it is, in this JVM, with its own context,
 *       its topology, its Flyway migrations and its actuator endpoint;
 *   <li>the API under test is this service, started against the same database, and it is read
 *       over HTTP through {@link TestRestTemplate} - the endpoints a client calls.
 * </ul>
 *
 * <p>What it asserts is the acceptance criterion of the milestone: the generated scenario is
 * observed through the public API. The vehicle the scenario parked is reported as
 * {@code STOPPED} with the position, the speed and the timestamp of the last generated event,
 * the two alerts of the two detections are listed with their stored metadata, the statistics
 * count them, and the counter of processed events is the one the processor publishes rather
 * than a number this API invents.
 *
 * <p>Two assumptions are stated rather than hidden, and both are properties of a test rather
 * than of the pipeline:
 *
 * <ul>
 *   <li>the generator is not run as a service, because its publishing loop is bound to the wall
 *       clock and to a configured rate. Its simulator, its event contract and its publishing
 *       mechanism are what this test drives, and the timeline it reads is the one the test
 *       moves; the service itself is covered by its own suite.
 *   <li>the scenario is published once, into a database the test owns: the containers are
 *       started for this class, so the counts asserted here are the counts of the scenario.
 * </ul>
 *
 * <p>Nothing waits on a fixed sleep: the assertions poll the API with Awaitility until the
 * pipeline has caught up or the timeout expires, and the stopped window is driven by the
 * timestamps of the telemetry instead of by the five minutes it describes. Without a Docker
 * daemon the class is skipped with the reason Testcontainers reports.
 */
@Testcontainers(disabledWithoutDocker = true)
@SpringBootTest(
        classes = LogisticsApiApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {
            // The suite of this service points at an in-memory database so it needs no server
            // (application-test.yml). The smoke test replaces that connection with the
            // container below; the properties are stated here because that file would
            // otherwise keep providing the driver and the schema policy of the in-memory run.
            "spring.datasource.driver-class-name=org.postgresql.Driver",
            "spring.datasource.hikari.read-only=true",
            "spring.jpa.hibernate.ddl-auto=none",
            "coobi.statistics.stream-processor.timeout=5s"
        })
class PipelineSmokeIT {

    private static final String LOCATION_TOPIC = "logistics.vehicle.location.v1";
    private static final Duration TIMEOUT = Duration.ofSeconds(120);
    private static final Duration POLL_INTERVAL = Duration.ofMillis(500);

    private static final int ONE_STREAM_THREAD = 1;

    @Container
    private static final KafkaContainer KAFKA =
            new KafkaContainer(DockerImageName.parse("apache/kafka:4.3.1"));

    @Container
    private static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>(DockerImageName.parse("postgres:18.6"));

    /** The processor as it starts in production, against the containers of this test. */
    private static ConfigurableApplicationContext processor;

    @BeforeAll
    static void startTheStreamProcessor() {
        processor = new SpringApplicationBuilder(StreamProcessorApplication.class)
                .web(WebApplicationType.SERVLET)
                .run(
                        // A profile of its own: the test resources of this service activate a
                        // profile of its suite, and the processor must not inherit it.
                        "--spring.profiles.active=integration-smoke",
                        // Both services are on the classpath of this test, so `application.yml`
                        // resolves to whichever comes first. Everything this test depends on is
                        // therefore stated: the name the processor logs and tags its metrics
                        // with, and a pool that is allowed to write, because the processor
                        // migrates and writes the database the API only reads.
                        "--spring.application.name=stream-processor",
                        // A random port, so the process can run next to the API under test.
                        "--server.port=0",
                        "--spring.datasource.url=" + POSTGRES.getJdbcUrl(),
                        "--spring.datasource.username=" + POSTGRES.getUsername(),
                        "--spring.datasource.password=" + POSTGRES.getPassword(),
                        "--spring.datasource.driver-class-name=org.postgresql.Driver",
                        "--spring.datasource.hikari.read-only=false",
                        // The migrations of the processor are the only definition of the schema,
                        // which is why this API can read the tables it never creates.
                        "--spring.flyway.enabled=true",
                        "--spring.flyway.locations=classpath:db/migration",
                        "--spring.jpa.hibernate.ddl-auto=none",
                        "--spring.kafka.bootstrap-servers=" + KAFKA.getBootstrapServers(),
                        "--spring.kafka.streams.application-id=coobi-stream-processor-smoke-test",
                        "--spring.kafka.streams.properties.num.stream.threads=" + ONE_STREAM_THREAD,
                        "--spring.kafka.streams.properties.commit.interval.ms=100",
                        "--spring.kafka.streams.properties.default.key.serde="
                                + "org.apache.kafka.common.serialization.Serdes$StringSerde",
                        "--spring.kafka.streams.properties.default.value.serde="
                                + "org.apache.kafka.common.serialization.Serdes$StringSerde",
                        "--coobi.kafka.initialization.enabled=true",
                        // The thresholds the scenario is built around, pinned here so the
                        // expectations of this test do not depend on which configuration file
                        // of the repository the processor picks up first.
                        "--coobi.processing.speed-limit-kph=" + GeneratedTelemetry.SPEED_LIMIT_KPH,
                        "--coobi.processing.stopped-window-seconds=" + GeneratedTelemetry.STOPPED_WINDOW_SECONDS,
                        "--coobi.processing.movement-threshold-meters=" + GeneratedTelemetry.MOVEMENT_THRESHOLD_METERS,
                        "--logging.level.org.apache.kafka=WARN");
    }

    @AfterAll
    static void stopTheStreamProcessor() {
        if (processor != null) {
            processor.close();
            processor = null;
        }
    }

    @DynamicPropertySource
    static void pipeline(DynamicPropertyRegistry registry) {
        // The API reads the database the processor writes, so both point at the container that
        // the processor migrated when it started.
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        // Statistics: where the API reads the processed-event counter from (MVP-5.4).
        registry.add("coobi.statistics.stream-processor.metrics-url", PipelineSmokeIT::processorMetricsUrl);
        // Publication: the API context puts the Kafka producer of the generator on the bus of
        // this test, which is the one the processor consumes.
        registry.add("spring.kafka.bootstrap-servers", KAFKA::getBootstrapServers);
    }

    private static String processorMetricsUrl() {
        String port = processor.getEnvironment().getProperty("local.server.port");
        assertThat(port)
                .as("the processor exposes its actuator on the port it bound")
                .isNotBlank();
        return "http://localhost:" + port + "/actuator/metrics";
    }

    @Autowired
    private TestRestTemplate rest;

    @Autowired
    private KafkaTemplate<String, String> kafkaTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void makesTheGeneratedScenarioVisibleThroughThePublicApi() {
        Instant startedAt = Instant.now().truncatedTo(ChronoUnit.SECONDS).plusSeconds(1);
        GeneratedTelemetry telemetry = GeneratedTelemetry.drivingAboveTheLimitThenParking(startedAt);
        String vehicleId = telemetry.vehicleId();

        telemetry.events().forEach(this::publish);

        await().atMost(TIMEOUT).pollInterval(POLL_INTERVAL).untilAsserted(() -> {
            JsonNode vehicle = vehicleOf(vehicleId);

            assertThat(vehicle.path("status").asText())
                    .as("the stopped detection of the processor is visible on the vehicle")
                    .isEqualTo("STOPPED");
            assertThat(vehicle.path("speed").asDouble())
                    .isEqualTo(telemetry.parkedEvent().data().speed());
            assertThat(vehicle.path("latitude").asDouble())
                    .isEqualTo(telemetry.parkedEvent().data().latitude());
            assertThat(vehicle.path("longitude").asDouble())
                    .isEqualTo(telemetry.parkedEvent().data().longitude());
            assertThat(vehicle.path("heading").asDouble())
                    .isEqualTo(telemetry.parkedEvent().data().heading());
            assertThat(Instant.parse(vehicle.path("lastUpdate").asText()))
                    .as("the read model reports the event the generator produced, not the write")
                    .isEqualTo(telemetry.parkedEvent().timestamp());
            assertThat(vehicle.path("updatedAt").asText()).isNotBlank();
        });

        // The same row through the fleet view, and through its status filter.
        assertThat(vehicleIdsOf("/api/v1/vehicles?size=100")).contains(vehicleId);
        assertThat(vehicleIdsOf("/api/v1/vehicles?status=STOPPED&size=100")).contains(vehicleId);
        assertThat(vehicleIdsOf("/api/v1/vehicles?status=MOVING&size=100")).doesNotContain(vehicleId);

        await().atMost(TIMEOUT).pollInterval(POLL_INTERVAL).untilAsserted(() -> {
            JsonNode page = bodyOf("/api/v1/alerts?vehicleId=" + vehicleId + "&size=10");
            assertThat(page.path("totalElements").asLong())
                    .as("both detections of the processor stored exactly one alert")
                    .isEqualTo(2L);

            List<JsonNode> alerts = elementsOf(page);
            JsonNode speeding = alertOfType(alerts, "SPEEDING_DETECTED");
            JsonNode stopped = alertOfType(alerts, "VEHICLE_STOPPED_DETECTED");

            assertThat(speeding.path("severity").asText()).isEqualTo("WARNING");
            assertThat(speeding.path("metadata").path("speed").asDouble())
                    .as("the alert carries the measured value of the telemetry")
                    .isEqualTo(telemetry.speedingEvent().data().speed());
            assertThat(speeding.path("metadata").path("threshold").asDouble())
                    .isEqualTo(GeneratedTelemetry.SPEED_LIMIT_KPH);
            assertThat(Instant.parse(speeding.path("occurredAt").asText()))
                    .isEqualTo(telemetry.speedingEvent().timestamp());

            assertThat(stopped.path("severity").asText()).isEqualTo("WARNING");
            assertThat(stopped.path("metadata").path("speed").asDouble()).isEqualTo(0.0);
            assertThat(stopped.path("metadata").path("threshold").asDouble())
                    .isEqualTo(GeneratedTelemetry.MOVEMENT_THRESHOLD_METERS);
            assertThat(Instant.parse(stopped.path("occurredAt").asText()))
                    .isEqualTo(telemetry.parkedAt());

            assertThat(speeding.path("eventId").asText()).isNotBlank();
            assertThat(speeding.path("createdAt").asText()).isNotBlank();
        });

        JsonNode statistics = bodyOf("/api/v1/statistics");
        assertThat(statistics.path("alertsGenerated").asLong())
                .as("the statistics count the rows the processor stored")
                .isEqualTo(2L);
        assertThat(statistics.path("activeVehicles").asLong())
                .as("the only vehicle of the scenario is parked")
                .isZero();
        assertThat(statistics.path("processedEvents").isNull())
                .as("the counter is read from the actuator of the processor, not invented")
                .isFalse();
        assertThat(statistics.path("processedEvents").asLong())
                .as("every record of the scenario was processed")
                .isGreaterThanOrEqualTo(telemetry.events().size());
    }

    /** Publishes one generated event the way the generator publishes it: keyed by vehicle. */
    private void publish(VehicleLocationEvent event) {
        kafkaTemplate.send(LOCATION_TOPIC, event.vehicleId(), serialize(event)).join();
    }

    private String serialize(VehicleLocationEvent event) {
        try {
            return objectMapper.writeValueAsString(event);
        } catch (JsonProcessingException failure) {
            throw new IllegalStateException("serializing " + event + " failed", failure);
        }
    }

    private JsonNode vehicleOf(String vehicleId) {
        ResponseEntity<JsonNode> response = rest.getForEntity("/api/v1/vehicles/" + vehicleId, JsonNode.class);
        assertThat(response.getStatusCode())
                .as("the vehicle of the scenario is readable")
                .isEqualTo(HttpStatus.OK);
        return response.getBody();
    }

    private JsonNode bodyOf(String path) {
        ResponseEntity<JsonNode> response = rest.getForEntity(path, JsonNode.class);
        assertThat(response.getStatusCode()).as(path).isEqualTo(HttpStatus.OK);
        return response.getBody();
    }

    private List<String> vehicleIdsOf(String path) {
        List<String> vehicleIds = new ArrayList<>();
        elementsOf(bodyOf(path)).forEach(vehicle -> vehicleIds.add(vehicle.path("vehicleId").asText()));
        return vehicleIds;
    }

    private static List<JsonNode> elementsOf(JsonNode page) {
        List<JsonNode> elements = new ArrayList<>();
        page.path("content").forEach(elements::add);
        return elements;
    }

    private static JsonNode alertOfType(List<JsonNode> alerts, String type) {
        return alerts.stream()
                .filter(alert -> type.equals(alert.path("type").asText()))
                .findFirst()
                .orElseThrow(() -> new AssertionError("no " + type + " alert in " + alerts));
    }
}
