package com.coobi.logistics.streamprocessor.processing;

import com.coobi.logistics.streamprocessor.event.AlertType;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import java.util.EnumMap;
import java.util.Map;
import java.util.Objects;

/**
 * Micrometer metrics of the telemetry pipeline (MVP-8.1).
 *
 * <p>Every meter is registered once, in the constructor, and every recording method is called
 * from the path it measures: the counters are incremented where a record is consumed, accepted,
 * rejected or turned into an alert, and the timer is recorded around the processing steps the
 * topology really performs. Nothing here is incremented at startup, so a value below the counts
 * of the topic is the absence of records rather than a missing instrument.
 *
 * <p>The names are the contract shared with {@code docs/observability.md} and with the
 * Prometheus scrape configuration. Because each counter name already ends in {@code _total},
 * the Prometheus registry publishes it unchanged instead of appending a second suffix.
 */
public final class TelemetryMetrics {

    /** Records consumed from the location topic, one per record the topology reads. */
    public static final String RECEIVED_METRIC = "logistics_events_received_total";

    /** Records accepted by the validation stage, so the topology keeps processing them. */
    public static final String PROCESSED_METRIC = "logistics_events_processed_total";

    /** Records rejected by the validation stage and routed to the dead letter topic. */
    public static final String FAILED_METRIC = "logistics_events_failed_total";

    /** Alerts generated, tagged with the {@code type} of the detection that produced them. */
    public static final String ALERTS_METRIC = "logistics_alerts_generated_total";

    /** Duration of one processing step of the topology. */
    public static final String PROCESSING_DURATION_METRIC = "logistics_event_processing_duration";

    private final Counter received;
    private final Counter processed;
    private final Counter failed;
    private final Map<AlertType, Counter> alerts;
    private final Timer processingDuration;

    public TelemetryMetrics(MeterRegistry meterRegistry) {
        MeterRegistry meters = Objects.requireNonNull(meterRegistry, "meterRegistry must not be null");
        this.received = Counter.builder(RECEIVED_METRIC)
                .description("Telemetry records consumed from the location topic")
                .register(meters);
        this.processed = Counter.builder(PROCESSED_METRIC)
                .description("Telemetry records accepted by the validation stage")
                .register(meters);
        this.failed = Counter.builder(FAILED_METRIC)
                .description("Telemetry records rejected by the validation stage")
                .register(meters);

        // Built from the enum values rather than from a fixed list, so a detection added to
        // AlertType is counted without touching this class.
        Map<AlertType, Counter> alertCounters = new EnumMap<>(AlertType.class);
        for (AlertType type : AlertType.values()) {
            alertCounters.put(type, alertCounter(meters, type));
        }
        this.alerts = Map.copyOf(alertCounters);

        this.processingDuration = Timer.builder(PROCESSING_DURATION_METRIC)
                .description("Time one processing step of the topology takes for one record")
                .register(meters);
    }

    private static Counter alertCounter(MeterRegistry meters, AlertType type) {
        return Counter.builder(ALERTS_METRIC)
                .description("Alerts generated by the processor, tagged with the detection type")
                .tag("type", type.name())
                .register(meters);
    }

    /** One record has been consumed from the location topic. */
    public void received() {
        received.increment();
    }

    /** One consumed record passed validation and is processed by the detections. */
    public void processed() {
        processed.increment();
    }

    /** One consumed record failed validation and is routed to the dead letter topic. */
    public void failed() {
        failed.increment();
    }

    /** One alert of the given detection type has been generated and forwarded. */
    public void alertGenerated(AlertType type) {
        alerts.get(Objects.requireNonNull(type, "type must not be null")).increment();
    }

    /**
     * The one timer of the pipeline. It is recorded once per processing step - the validation
     * of a consumed record, each detection an accepted record feeds, and the dead letter
     * mapping of a rejected one - so its count is the number of steps the topology ran and
     * {@code total_time / count} is the average duration of one step.
     */
    public Timer processingDuration() {
        return processingDuration;
    }
}
