-- MVP-4.2: the vehicle registry and the latest known state of every vehicle.
--
-- PostgreSQL is not an event store here: `vehicles` holds one row per vehicle ever seen
-- and `vehicle_latest_state` holds exactly one row per vehicle, overwritten in place.
-- Telemetry history is deliberately not persisted (see the milestone non-goals).
--
-- Written for PostgreSQL 18 and kept executable under an in-memory database in
-- PostgreSQL compatibility mode, which is what the persistence tests use.

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Surrogate key for future references, contract key for this service.
    vehicle_id VARCHAR(64) NOT NULL,
    -- Instant the vehicle was first seen; never updated afterwards.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT vehicles_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS vehicle_latest_state (
    vehicle_id VARCHAR(64) PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION NOT NULL,
    heading DOUBLE PRECISION NOT NULL,
    status VARCHAR(16) NOT NULL,
    -- Timestamp of the telemetry event, not of the write.
    last_update TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Timestamp of the write, so a stalled vehicle is distinguishable from a stale row.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT vehicle_latest_state_status_check CHECK (status IN ('MOVING', 'STOPPED')),
    -- One state row per vehicle: the row is created with its vehicle and cascades with it.
    CONSTRAINT vehicle_latest_state_vehicle_id_fkey
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id) ON DELETE CASCADE
);

-- Fleet views read the newest state first; the status index serves "which vehicles are
-- stopped right now" without a sequential scan.
CREATE INDEX IF NOT EXISTS vehicle_latest_state_last_update_idx
    ON vehicle_latest_state (last_update DESC);

CREATE INDEX IF NOT EXISTS vehicle_latest_state_status_last_update_idx
    ON vehicle_latest_state (status, last_update DESC);
