-- MVP-4.3: alerts accepted by the processor, stored idempotently.
--
-- `event_id` is unique, so replaying a Kafka record - or a duplicate delivery of the same
-- alert - can never create a second row. `vehicle_id` is deliberately not a foreign key:
-- the two detection branches consume the same telemetry record independently, so an alert
-- can reach this table before the state branch has written the vehicle row.

CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- eventId of the alert contract; the idempotency key of this table.
    event_id UUID NOT NULL,
    vehicle_id VARCHAR(64) NOT NULL,
    -- eventType of the alert contract: SPEEDING_DETECTED | VEHICLE_STOPPED_DETECTED.
    type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    -- Timestamp of the telemetry event that triggered the alert.
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Instant the row was written.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    -- AlertData of the alert contract, kept verbatim as JSON.
    metadata JSONB NOT NULL,
    CONSTRAINT alerts_event_id_key UNIQUE (event_id),
    CONSTRAINT alerts_type_check CHECK (type IN ('SPEEDING_DETECTED', 'VEHICLE_STOPPED_DETECTED')),
    CONSTRAINT alerts_severity_check CHECK (severity IN ('WARNING'))
);

-- Operator views: alerts of one vehicle in reverse chronological order, and the newest
-- alerts of the fleet.
CREATE INDEX IF NOT EXISTS alerts_vehicle_id_occurred_at_idx
    ON alerts (vehicle_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS alerts_occurred_at_idx
    ON alerts (occurred_at DESC);
